# Generated by Django 4.2.23 on 2025-08-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Photo'),
        ),
    ]
