# Generated by Django 4.2.23 on 2025-10-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_siteconfig_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Client contacté'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
