# Generated by Django 4.2.23 on 2025-08-06 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
