# Generated by Django 4.2.23 on 2025-08-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, '★★★★★ - Excellent'), (4, '★★★★☆ - Très bon'), (3, '★★★☆☆ - Bon'), (2, '★★☆☆☆ - Moyen'), (1, '★☆☆☆☆ - Décevant')], null=True, verbose_name='Note'),
        ),
    ]
